language: rust
sudo: true
rust:
- beta
os:
- linux
dist: xenial
script:
- sudo apt-get install libgtk-3-dev
- cargo build --release
deploy:
  provider: releases
  api_key:
    secure: lXF/2UPYOcsYQxuBCN5GzF1JylGtS8wCCbEppVwrSq+eQWVs1xFY+NDD4o/pjk7SkGXu8Aj7FZCBfANL8KJRM7moqdbR4+z7v7IcpngLgeT+bEaZS+f67prqKQg2kXlNVSpYzKHH7aceZVcJBWLJTOu8NQ8bQo4EX/TLfspqgQX3JzMBzqUP5MaoV5sdlotaOo3hRJxmbWmy8m+FkeV7r8K/mqXoXpGPlU8uRKkzZ+QdLM1VIdFi2eUFpdX43KWDKst6i5ppGHu/C/qKsl6enaTIcrIb90UjuG9KOMhFsaxhdvDvHTq582GcKMOyK9jXBwgkGHp0/wzSWgrmjARyn422vC1YuUBpQLv2Iv8LQ8JwT2eeGNMwVu5+eAav2qTeBH4OSMVTb6ANtzoo2QEeShqX2UjcZNPh6VMvKD+CapL3oqOfQBlV95AgNvgKuu9klsTQoQ4JFSnXHpnzn+OiGzb/QuGs5srhNRM1RWTxR8foDJPqYLHe0AlUYPenE2VV/OSyouUfyqY1U0x+zirezYqz/AesFdpajZCSuu5dUMCzf5w48c8BuVJlPw515ATgfeGKaTAO3OYTxoSOb0a4DR+0Mp2ss2w0WkJcFSeb2AL246stE/C6cSWH/stSJ6OHZH8WjlyPJbnAgtRKTEoH1vCth/TYn3tt7FWGQKDS22Y=
  file: target/release/bool-table
  on:
    repo: sigmaSd/Truth-table
